# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Champions', '0002_alter_champion_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='icon',
            new_name='image',
        ),
    ]
