# Generated by Django 4.2.1 on 2023-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Champions', '0007_alter_champion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='image',
            field=models.ImageField(upload_to='C:/Users/rodry/Desktop/Draft simulator/Draft-Simulator/Django/DraftSimulator/'),
        ),
    ]
